### ISSUE TITLE
Unreachable code in time.rs

### ISSUE THREAD

**Issue by AaronErhardt** [SebastianBraun01/rustuino#4]
Sorry that it took me so long to come back to this project but I had a lot more work to do than I anticipated...

This if will always be false: https://github.com/SebastianBraun01/rustuino/blob/5a60ec164c945836d60a8b166e4dbbd678ac80fb/src/time.rs#L155

Because the same condition is checked earlier here: https://github.com/SebastianBraun01/rustuino/blob/5a60ec164c945836d60a8b166e4dbbd678ac80fb/src/time.rs#L138

IMO we should use clippy more often because it actually helped me discover this.

**Comment by SebastianBraun01** [comment]
I already fixed that problem with a match statement that selects the timer.

```rust
  match timer {
    1 => {...},
    2 => {...},
    3 => {...},
    4 => {...},
    _  => {
      rtt_target::rprintln!("Timer{} is not a valid timer! | setup_pwm()", timer);
      return Err(GpioError::ConfigurationError);
    }
  };
```
