### ISSUE TITLE
rise_t always set to 1

### ISSUE THREAD

**Issue by AaronErhardt** [SebastianBraun01/rustuino#5]
This line of the code always sets rise_t to 1 (or 0 + 1):
https://github.com/SebastianBraun01/rustuino/blob/5a60ec164c945836d60a8b166e4dbbd678ac80fb/src/i2c.rs#L37

Is this intentional?

**Comment by SebastianBraun01** [comment]
I think the formula that is use for rise_t is wrong. I need to look it up in the datasheet again.

**Comment by SebastianBraun01** [comment]
Fixed the formula
`let rise_t = (BUS_FREQ / 1000000) + 1;`
